### ISSUE TITLE
thread 'rustc' panicked at 'not implemented', src/debuginfo.rs:46:9

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc_codegen_gcc#81]
This happens when using `--emit llvm-ir`.

https://rust.godbolt.org/z/YnjzoKaKn

```rust
extern "C" {
    fn my_c_fn(a: u32);
}

pub unsafe fn uninit() {
    let u = std::mem::MaybeUninit::uninit().assume_init();
    my_c_fn(u);
}
```

```
thread 'rustc' panicked at 'not implemented', src/debuginfo.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (ccffcafd5 2021-08-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=librustc_codegen_gcc.so -C panic=abort -C debuginfo=1 -C opt-level=3 -C debuginfo=0 --crate-type rlib

query stack during panic:
end of query stack
Compiler returned: 101
```

**Comment by antoyo** [comment]
Closing in favor of #69.
